### ISSUE TITLE
Ubuntu 18.04.3 compiling error: failed to run custom build command for `sass-sys v0.4.7`

### ISSUE THREAD

**Issue by jylandry** [rust-lang/blog.rust-lang.org#471]
I try to compile this project using the recommended procedure.  However, I get an error that I don't understand how to solved.

Final result:  **error: failed to run custom build command for `sass-sys v0.4.7`**

OS:  Ubuntu 18.04.3
Rust:  rustc 1.39.0 ...  Then, try the nightly version: rustc 1.39.0 (4560ea788 2019-11-04)

 **Full listing of the "build/compile"**

```
git clone https://github.com/rust-lang/blog.rust-lang.org
Cloning into 'blog.rust-lang.org'...
remote: Enumerating objects: 418, done.
remote: Counting objects: 100% (418/418), done.
remote: Compressing objects: 100% (281/281), done.
remote: Total 6354 (delta 119), reused 253 (delta 24), pack-reused 5936
Receiving objects: 100% (6354/6354), 13.55 MiB | 1.05 MiB/s, done.
Resolving deltas: 100% (3658/3658), done.
jylandry@seattle:~/test-rust-blob$  cd blog.rust-lang.org
jylandry@seattle:~/test-rust-blob/blog.rust-lang.org$ cargo run
   Compiling proc-macro2 v0.4.24
   Compiling unicode-xid v0.1.0
   Compiling libc v0.2.44
   Compiling memchr v2.2.1
   Compiling ucd-trie v0.1.1
   Compiling serde v1.0.80
   Compiling maplit v1.0.1
   Compiling lazy_static v1.4.0
   Compiling pkg-config v0.3.14
   Compiling ryu v0.2.7
   Compiling unicode-width v0.1.5
   Compiling regex-syntax v0.6.12
   Compiling cfg-if v0.1.6
   Compiling ansi_term v0.11.0
   Compiling vec_map v0.8.1
   Compiling itoa v0.4.3
   Compiling strsim v0.7.0
   Compiling same-file v1.0.4
   Compiling bitflags v1.0.4
   Compiling linked-hash-map v0.5.1
   Compiling entities v1.0.1
   Compiling quick-error v1.2.2
   Compiling dtoa v0.4.3
   Compiling unicode_categories v0.1.1
   Compiling typed-arena v1.4.1
   Compiling fs_extra v1.1.0
   Compiling pest v2.0.2
   Compiling thread_local v0.3.6
   Compiling textwrap v0.10.0
   Compiling log v0.4.6
   Compiling walkdir v2.2.7
   Compiling sass-sys v0.4.7
   Compiling yaml-rust v0.4.2
   Compiling pest_meta v2.0.3
error: failed to run custom build command for `sass-sys v0.4.7`

Caused by:
  process didn't exit successfully: `/home/jylandry/test-rust-blob/blog.rust-lang.org/target/debug/build/sass-sys-e6d404158bac71cd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'error running make: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55cceabff984 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55cceabff984 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55cceabff984 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55cceabff984 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55cceac1f28c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55cceabfc847 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55cceac01e45 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55cceac01e45 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55cceac01e45 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55cceac01b36 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55cceac02495 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55cceac02032 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55cceac01f26 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55cceac1c99a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55cceac1ca97 - core::result::unwrap_failed::ha8b77e6004f0ba38
                               at src/libcore/result.rs:1165
  15:     0x55cceabb9028 - core::result::Result<T,E>::expect::h44b1e8323d7b92d2
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:960
  16:     0x55cceabb82dc - build_script_build::compile::h61abb081b403005a
                               at /home/jylandry/.cargo/registry/src/github.com-1ecc6299db9ec823/sass-sys-0.4.7/build.rs:71
  17:     0x55cceabb8950 - build_script_build::main::h5796751c30d880b2
                               at /home/jylandry/.cargo/registry/src/github.com-1ecc6299db9ec823/sass-sys-0.4.7/build.rs:164
  18:     0x55cceabba3b0 - std::rt::lang_start::{{closure}}::h99947bfae23f9eab
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  19:     0x55cceac01f13 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  20:     0x55cceac01f13 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  21:     0x55cceac0967a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  22:     0x55cceac0298d - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  23:     0x55cceac0298d - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  24:     0x55cceac0298d - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  25:     0x55cceabba389 - std::rt::lang_start::hd6e09872acf0aa10
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  26:     0x55cceabb898a - main
  27:     0x7fe406c3eb97 - __libc_start_main
  28:     0x55cceabb699a - _start
  29:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Zexbe** [comment]
I was able to install rustup on ubuntu 18, switch to nightly, and build the project.
Is this still an issue for you?

**Comment by Zexbe** [comment]
I just realized what your problem might be.

Try this
```
apt update
apt install build-essential
```

**Comment by jylandry** [comment]
I try the "build-essential" install.  The system told me --  Already to the latest version.

**Comment by Zexbe** [comment]
Okay try this rustup update

**Comment by jylandry** [comment]
I did a git pull and cargo run.  
It seem to compile...    Does not run yet... but it is likely because it need some installation step.

**Comment by jylandry** [comment]
Work perfectly, thanks a lot
